# Docker-compose for Jobsity

version: '3.7'
 
services:
    rabbitmq:
        image: jobsityrabbitmq:latest
        build: 
            context: ./rabbitmq
            dockerfile: Dockerfile
            target: jobsityrabbitmq
        hostname: app-rabbitmq
        ports:
            - 5672:5672
            - 15670:15670
            - 15672:15672
            - 15674:15674
            - 4369:4369
            - 25672:25672
            - 1883:1883
            - 8883:8883
            - 61613:61613 
        volumes:
            - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
            - ./conf/myrabbit.conf:/etc/rabbitmq/rabbitmq.config
        environment:
            RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
            RABBITMQ_DEFAULT_USER: rabbitmq
            RABBITMQ_DEFAULT_PASS: rabbitmq
            RABBITMQ_DEFAULT_VHOST: /